### ISSUE TITLE
Unfulfilled amount error

### ISSUE THREAD

**Issue by 34r7h** [Python-Cardano/pycardano#56] opened 2022-06-29 13:59 UTC
Hello Jerry. Hope all is good. 

Maybe this is solved in a recent commit but pip is still giving me version 0.5.0. Please push if you tackled this.

I'm still getting funky errors on creating txs with addresses that have one or few txs. The index of available inputs is out of line. I'm guessing this is a problem with blockfrost's context. One address has 2 txs, indexed at 1 and 3 respectively. I'm pretty sure that's causing txs to fail.

<img width="355" alt="Screen Shot 2022-06-29 at 19 23 38" src="https://user-images.githubusercontent.com/2566560/176454409-18ffa7f8-e238-4eca-81af-cf5ad3c12450.png">
<img width="439" alt="Screen Shot 2022-06-29 at 19 23 22" src="https://user-images.githubusercontent.com/2566560/176454420-20a4554d-1b97-480b-aaf5-658dbfa48090.png">

**Comment by 34r7h** [comment] 2022-06-29 14:03
blockfrost has had some hiccups recently.. not getting 'some' balances updated and such. this might be the issue as well. i made a ticket with them and they responded that they knew the issue and it should be solved but i didn't ask about the indexing issue.

**Comment by 34r7h** [comment] 2022-06-30 08:17
Details of failing tx build:

Available UTXOs:
```
utxos [
{'input': {'index': 0,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 1379280,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}}, 

{'input': {'index': 1,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 7228558, 'multi_asset': {}},
 'datum_hash': None}}, 

{'input': {'index': 0,
 'transaction_id': TransactionId(hex='233a835316f4c27bceafdd190639c9c7b834224a7ab7fce13330495437d977fa')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5639430, 'multi_asset': {}},
 'datum_hash': None}}] 
```

Builder:
```
TransactionBuilder(context=<pycardano.backend.blockfrost.BlockFrostChainContext object at 0x10f447e80>, utxo_selectors=[<pycardano.coinselection.RandomImproveMultiAsset object at 0x110e87a90>, <pycardano.coinselection.LargestFirstSelector object at 0x110e87ac0>], execution_memory_buffer=0.2, execution_step_buffer=0.2, ttl=None, validity_start=None, auxiliary_data=None, native_scripts=None, mint=None, required_signers=None, collaterals=[], certificates=None, withdrawals=None, _inputs=[{'input': {'index': 0,
 'transaction_id': TransactionId(hex='233a835316f4c27bceafdd190639c9c7b834224a7ab7fce13330495437d977fa')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5639430, 'multi_asset': {}},
 'datum_hash': None}}, {'input': {'index': 0,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 1379280,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}}], _excluded_inputs=[], _input_addresses=[addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr], _outputs=[{'address': addr1qxx7lc2kyrjp4qf3gkpezp24ugu35em2f5h05apejzzy73c7yf794gk9yzhngdse36rae52c7a6rv5seku25cd8ntves7f5fe4,
 'amount': {'coin': 1000000,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}, {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5847225, 'multi_asset': {}},
 'datum_hash': None}], _fee=171485, _datums={}, _inputs_to_redeemers={}, _minting_script_to_redeemers=[], _inputs_to_scripts={}, _should_estimate_execution_units=None) 
```

**Comment by cffls** [comment] 2022-06-30 18:21
It seems to me that the failed transaction pasted above doesn't satisfy the minimum lovelace amount.
See this output:

```
_outputs=[{'address': addr1qxx7lc2kyrjp4qf3gkpezp24ugu35em2f5h05apejzzy73c7yf794gk9yzhngdse36rae52c7a6rv5seku25cd8ntves7f5fe4,
 'amount': {'coin': 1000000,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}
```
You attached a NFT to it, but it only has 1ADA, which can't hold any multi-asset. If you try 1.5 ADA, it may work.

**Comment by 34r7h** [comment] 2022-07-01 06:25
I'm not following yet.. the address has a total of 14 ada in 3 utxos but
the builder isn't taking from the available txs. I've tried sending various
amounts big and small and keep getting an insufficient amount error, hence
falling back to building a raw transaction for token txs.

**Comment by cffls** [comment] 2022-07-01 06:58
I think the problem you posted is not caused by utxo selection. UTxO selection doesn't necessary select all available UTxOs. Instead, the problem might be that you were trying to send an asset with only 1ADA, which is insufficient according to the min lovelace rule. Also, could you please post the entire log, including the actually exception being thrown and the Transaction input and output. It is not easy for me to guess what the real problem is without complete information. Thank you!

**Comment by 34r7h** [comment] 2022-07-01 08:09
Sure, stout for utxos, builder, and error message below. I upped the lovelace to 3,000,000 in this example. 

Notice the input holding the nft has only 1.3 ada but there's more than sufficient amounts of lovelace in the following 2 utxos to cover the 3 ada + tx fee. The builder is only taking the first utxo as an input which does not have a sufficient amount to cover the total tx amount.

## utxos
```
[{'input': {'index': 0,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 1379280,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}}, 

{'input': {'index': 1,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 7228558, 'multi_asset': {}},
 'datum_hash': None}}, 

{'input': {'index': 0,
 'transaction_id': TransactionId(hex='233a835316f4c27bceafdd190639c9c7b834224a7ab7fce13330495437d977fa')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5639430, 'multi_asset': {}},
 'datum_hash': None}}] 
```
## Builder
```
TransactionBuilder(context=<pycardano.backend.blockfrost.BlockFrostChainContext object at 0x10965be80>, utxo_selectors=[<pycardano.coinselection.RandomImproveMultiAsset object at 0x10b0a3a90>, <pycardano.coinselection.LargestFirstSelector object at 0x10b0a3ac0>], execution_memory_buffer=0.2, execution_step_buffer=0.2, ttl=None, validity_start=None, auxiliary_data=None, native_scripts=None, mint=None, required_signers=None, collaterals=[], certificates=None, withdrawals=None, _inputs=[{'input': {'index': 0,
 'transaction_id': TransactionId(hex='233a835316f4c27bceafdd190639c9c7b834224a7ab7fce13330495437d977fa')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5639430, 'multi_asset': {}},
 'datum_hash': None}}, {'input': {'index': 0,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 1379280,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}}], _excluded_inputs=[], _input_addresses=[addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr], _outputs=[{'address': addr1qxx7lc2kyrjp4qf3gkpezp24ugu35em2f5h05apejzzy73c7yf794gk9yzhngdse36rae52c7a6rv5seku25cd8ntves7f5fe4,
 'amount': {'coin': 3000000,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}, {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 3847225, 'multi_asset': {}},
 'datum_hash': None}], _fee=171485, _datums={}, _inputs_to_redeemers={}, _minting_script_to_redeemers=[], _inputs_to_scripts={}, _should_estimate_execution_units=None) 
```

## Error Traceback
```
Traceback (most recent call last):
  File "/Users/34r7h/a/cardano-python-js/python/createtx.py", line 97, in <module>
    signed_tx = builder.build_and_sign([sk], change_address=address)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/txbuilder.py", line 929, in build_and_sign
    tx_body = self.build(change_address=change_address, merge_change=merge_change)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/txbuilder.py", line 865, in build
    self._add_change_and_fee(change_address, merge_change=merge_change)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/txbuilder.py", line 422, in _add_change_and_fee
    changes = self._calc_change(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pycardano/txbuilder.py", line 336, in _calc_change
    raise InvalidTransactionException(
pycardano.exception.InvalidTransactionException: The input UTxOs cannot cover the transaction outputs and tx fee. 
Inputs: [{'input': {'index': 0,
 'transaction_id': TransactionId(hex='233a835316f4c27bceafdd190639c9c7b834224a7ab7fce13330495437d977fa')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 5639430, 'multi_asset': {}},
 'datum_hash': None}}, {'input': {'index': 0,
 'transaction_id': TransactionId(hex='cb00474e85a32a9cda5d5b53d0705abec9c1b7b27836331fd00c689c79988639')},
 'output': {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 1379280,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}}] 
Outputs: [{'address': addr1qxx7lc2kyrjp4qf3gkpezp24ugu35em2f5h05apejzzy73c7yf794gk9yzhngdse36rae52c7a6rv5seku25cd8ntves7f5fe4,
 'amount': {'coin': 3000000,
 'multi_asset': {ScriptHash(hex='c4d5ae259e40eb7830df9de67b0a6a536b7e3ed645de2a13eedc7ece'): {AssetName(b'x your eyes'): 1}}},
 'datum_hash': None}, {'address': addr1q872eujv4xcuckfarjklttdfep7224gjt7wrxkpu8ve3v6g4x2yx743payyucr327fz0dkdwkj9yc8gemtctgmzpjd8qcdw8qr,
 'amount': {'coin': 3847225, 'multi_asset': {}},
 'datum_hash': None}] 
```

**Comment by 34r7h** [comment] 2022-07-01 08:59
btw, pip is still serving pycardano version 0.5.0 which I don't think contains your latest commits. Is there a chance that this issue is already fixed in your recent work?

**Comment by cffls** [comment] 2022-07-09 23:48
I added the example you provided as a unit test in this example [here](https://github.com/cffls/pycardano/commit/38acb8713715344f1563f8a266cb66c9708bf6c4n), which has passed. At the moment, I don't know how to reproduce the issue you encountered. I will look further if you could provide a runnable python script that can reproduce the issue you described.

**Comment by cffls** [comment] 2022-08-12 21:54
Closing this issue as there is no update for a month. Please feel free to reopen this if you could provide a runnable python script that can reproduce the issue. Thanks!

**Closed as completed by cffls** 2022-08-12 21:54 UTC
